### PR TITLE
Icon Addition

### PR DESCRIPTION
**Pull request by TUOBCAN**
- Changed the size of the title on learn more section and placed additional font awesome icons with it.
- Used the description section of developers that was empty before for their socials. 
- Updated profile picture url's

### CODE REVIEW

**Comment by dangerousones** [comment]
Got a GitHub sites page on this so I can see how it looks?

**Comment by dangerousones** [comment]
Pfp icons are messed up, at least on mobile

**Comment by TUOBCAN** [comment]
> Pfp icons are messed up, at least on mobile

Updated uɐWɯopuɐꓤꓶƎ#4449 and Naamloos#2887 pfp
What was originally wrong with it?

**Comment by dangerousones** [comment]
Seems good

**Pull request merged**
